Updated openjdk:8u191 to openjdk:8u212
Updated openjdk:8u191 to openjdk:8u212 due to missing manifest file :
Error: buildx failed with: error: failed to solve: rpc error: code = Unknown desc = openjdk:8u191-jre-alpine3.9: failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:83eacc6682cb7995a43d0e60f89f76b0c1e33f29b299273d96321fc97b2911fc (application/vnd.docker.distribution.manifest.v1+json) from remote: not found